const StudentsActionType = {
    FETCH_ALL_STUDENTS: "FETCH_ALL_STUDENTS",
    FETCH_SINGLE_STUDENT: "FETCH_SINGLE_STUDENT",
    FETCH_ALL_STUDENTS: "FETCH_ALL_STUDENTS",
    FETCH_SINGLE_STUDENT: "FETCH_SINGLE_STUDENT",
    ADD_STUDENT: "ADD_STUDENT",
    DELETE_STUDENT: "DELETE_STUDENT",
    UPDATE_STUDENT:" UPDATE_STUDENT"
}
export default StudentsActionType;